### ISSUE TITLE
TODO ACTION 기능 작업

### ISSUE THREAD

**Issue by muffin9** [muffin9/TStodoist#30]
## 예상 동작

카드 등록, 수정, 삭제, 이동 / 칼럼 수정 같은 액션들을 네비게이션으로 모두 볼 수 있는 기능

- [x] 🚧 헤더쪽 메뉴 아이콘을 누르면 애니메이션 동작 추가
- [x] #61
- [x] 🚧 실제 action 관련 테이블 설계
- [x] #66
- [x] 🚧 마우스 Drag & Drop 시에도 정상적인 동작 확인
- [x] 🚧 Todo, Column 각각 액션 어떤식으로 보여줄지 설계 후 구현.
